# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - dsc-fpt

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Setup .npmrc
        run: |
          echo "legacy-peer-deps=true" >> .npmrc
          echo "strict-peer-dependencies=false" >> .npmrc

      - name: Clean and prepare
        run: |
          rm -rf node_modules package-lock.json
          npm cache clean --force

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
          npm install ajv@^8.0.0 --save
          npm install ajv-keywords@^5.0.0 --save
          npm install schema-utils@^4.0.0 --save-dev
          npm install terser-webpack-plugin@^5.0.0 --save-dev
          npm install react-scripts@5.0.1 --save-dev

      - name: Install additional dependencies
        run: |
          npm install @babel/plugin-proposal-private-property-in-object --save-dev
          npm install @babel/runtime --save

      - name: Update browserslist
        run: npx update-browserslist-db@latest

      - name: Build
        env:
          CI: false
        run: |
          npm rebuild
          npm run build --if-present

      - name: Test
        env:
          CI: false
        run: |
          npm test -- --passWithNoTests --watchAll=false || true

      - name: Prepare artifact
        run: |
          mkdir artifact
          cp -r build/* artifact/
          cp package.json artifact/
          cp package-lock.json artifact/ || true
          cp .npmrc artifact/ || true

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: artifact
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'dsc-fpt'
          slot-name: 'Production'
          package: .
